shannon-fano: add missing algorithm include
Fixes:

  .../src/shannon-fano.cpp: In function ‘void txtz::shannon_fano(std::vector<ngram_t>&, bool)’:
  .../src/shannon-fano.cpp:68:18: error: ‘sort’ is not a member of ‘std’; did you mean ‘qsort’?
     68 |             std::sort(std::begin(p), std::end(p), [](ngram_t const &a, ngram_t const &b)
        |                  ^~~~
        |                  qsort