util: add missing cstdint include
Fixes:

  .../src/util.cpp: In function ‘std::string util::escaped(const std::string&)’:
  .../src/util.cpp:52:111: error: ‘uint8_t’ was not declared in this scope
     52 | std::oct << std::setfill('0') << static_cast<unsigned int>((uint8_t)c);
        |                                                             ^~~~~~~