txtz: add missing cstdint include
Fixes:

  .../src/txtz.hpp:49:21: error: ‘uint8_t’ was not declared in this scope
     49 |         std::vector<uint8_t> compress(std::string const &, std::size_t &);
        |                     ^~~~~~~